id: I436D66B7
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T04:15:47+00:00'
last_modified: '2022-06-08T02:17:50.587447+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W20559
  title: གཏམ་གྱི་ཚོགས་ཐེག་པའི་རྒྱ་མཚོ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    0934:
      image_group_id: I4984
      title: ''
      total_pages: 675
      order: 1
      base_file: 0934.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
