id: P004610
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-17 11:44:15.045493
source_metadata:
  id: bdr:W20559
  title: གཏམ་གྱི་ཚོགས་ཐེག་པའི་རྒྱ་མཚོ
  author: ''
  volumes:
    c08f08fb2b17482c855d4b1c5c1959e0:
      image_group_id: I4984
      title: ''
      volume_number: 1
      total_pages: 675
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
